### ISSUE TITLE
Run Leela(OpenCL Accleration) on Android

### ISSUE THREAD

**Issue by uestccokey** [gcp/leela-zero#1679]
I compiled leela that support opencl acceleration and it can runs on Android.

My test phone is XiaoMi 4:
CPU Snapdragon801(ARMv7a)
GPU Adreno330
Android 6.0.1

But when leela starts, I met an error after the tuner.
As follows:

```
1|root@cancro:/data/local # ./leela -g -w 57.gz
./leela -g -w 57.gz
Using 2 thread(s).
RNG seed: 14892193533682884522
Detecting residual layers...v1...64 channels...5 blocks.
Initializing OpenCL (autodetect precision).
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 QUALCOMM build: commit #ec93b97 changeid #I48a9d37399 Date: 11/17/16 Thu Local Branch:  Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013
Platform profile: EMBEDDED_PROFILE
Platform name:    QUALCOMM Snapdragon(TM)
Platform vendor:  QUALCOMM
Device ID:     0
Device name:   QUALCOMM Adreno(TM)
Device type:   GPU
Device vendor: QUALCOMM
Device driver: OpenCL 1.2 QUALCOMM build: commit #ec93b97 changeid #I48a9d37399 Date: 11/17/16 Thu Local Branch:  Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013 Compiler E031.29.00.00
Device speed:  1 MHz
Device cores:  4 CU
Device score:  112
Selected platform: QUALCOMM Snapdragon(TM)
Selected device: QUALCOMM Adreno(TM)
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 3.9311 ms (1.9 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 2.3685 ms (3.1 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.8636 ms (4.0 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.6544 ms (4.5 GFLOPS)
(6/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.6239 ms (4.5 GFLOPS)
(14/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.3377 ms (5.5 GFLOPS)
(66/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.3036 ms (5.7 GFLOPS)
(131/290) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 1.0925 ms (6.7 GFLOPS)
Wavefront/Warp size: 128
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 QUALCOMM build: commit #ec93b97 changeid #I48a9d37399 Date: 11/17/16 Thu Local Branch:  Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013
Platform profile: EMBEDDED_PROFILE
Platform name:    QUALCOMM Snapdragon(TM)
Platform vendor:  QUALCOMM
Device ID:     0
Device name:   QUALCOMM Adreno(TM)
Device type:   GPU
Device vendor: QUALCOMM
Device driver: OpenCL 1.2 QUALCOMM build: commit #ec93b97 changeid #I48a9d37399 Date: 11/17/16 Thu Local Branch:  Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1.3_RB1.06.00.01.181.013 Compiler E031.29.00.00
Device speed:  1 MHz
Device cores:  4 CU
Device score:  112
Selected platform: QUALCOMM Snapdragon(TM)
Selected device: QUALCOMM Adreno(TM)
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 290 valid configurations.
(1/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 3.5789 ms (2.1 GFLOPS)
(2/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 2.6663 ms (2.8 GFLOPS)
(3/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 2.2868 ms (3.2 GFLOPS)
(4/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 2.2634 ms (3.3 GFLOPS)
(5/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.7092 ms (4.3 GFLOPS)
(66/290) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 1.5332 ms (4.8 GFLOPS)
(125/290) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 1.3404 ms (5.5 GFLOPS)
(164/290) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 1.1030 ms (6.7 GFLOPS)
Wavefront/Warp size: 128
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
BLAS Core: ARMV7
Error in convolve3: clEnqueueNDRangeKernel: -54
Error in convolve3: clEnqueueNDRangeKernel: -54
terminating with uncaught exception of type cl::Error: clEnqueueNDRangeKernel
/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type cl::Error: clEnqueueNDRangeKernel" failed
[1] + Stopped (signal)     ./leela -g -w 57.gz 
root@cancro:/data/local # 
```

**Can anyone help me?**

It's my compiled leela
https://drive.google.com/open?id=1sqyenhTNfv-Eshb0yD4LbV0b1ORa8oTO

and It's my app AQGO(with leela not acceleration)
https://drive.google.com/open?id=1mmFpi_ia8SiWoDqINCQfREuw3vXJPB_p
![device-2018-08-01-232346](https://user-images.githubusercontent.com/7234924/43531779-1f2ff170-95e3-11e8-9291-9264e1e973c1.png)

**Comment by gcp** [comment]
OpenCL error -54 is:

#define CL_INVALID_WORK_GROUP_SIZE -54

**Comment by gcp** [comment]
If you can put ```try catch``` blocks around each call to queue.enqueueNDRangeKernel in convolve3 that might help narrowing down the exact kernel invocation and parameters that are problematic.

**Comment by Ttl** [comment]
I suspect that the issue is with `out_transform_fused_bn_in` kernel trying to use too large local size that can't fit on the device. Wavefront size in the logs is 128 so it's trying to use (2, 128, 1) local size. The resource use of the kernel can heavily limit the local size on this GPU (https://developer.qualcomm.com/forum/qdn-forums/software/adreno-gpu-sdk/33328).

If the problem is with that kernel these changes should fix it:

```diff
diff --git a/src/OpenCL.cpp b/src/OpenCL.cpp
index f22278a..0b5d478 100644
--- a/src/OpenCL.cpp
+++ b/src/OpenCL.cpp
@@ -207,9 +207,6 @@ void OpenCL_Network<net_t>::forward(const std::vector<float>& input,
             auto conv_weights = begin(layer.weights);
             auto bn_weights = begin(layer.weights) + 1;
             auto skip_next_in_trans = false;
-            if (niter->is_residual_block) {
-                skip_next_in_trans = true;
-            }
 
             convolve3(opencl_context,
                      layer.channels,
@@ -242,13 +239,10 @@ void OpenCL_Network<net_t>::forward(const std::vector<float>& input,
                       conv1_weights,
                       nullptr,
                       bn1_weights,
-                      skip_in_trans, true, false,
+                      skip_in_trans, false, false,
                       batch_size);
 
             auto skip_next_in_trans = false;
-            if (niter->is_residual_block) {
-                skip_next_in_trans = true;
-            }
             convolve3(opencl_context,
                       layer.channels,
                       layer.outputs,
@@ -259,7 +253,7 @@ void OpenCL_Network<net_t>::forward(const std::vector<float>& input,
                       conv2_weights,
                       &inBuffer,
                       bn2_weights,
-                      true, skip_next_in_trans, true,
+                      false, skip_next_in_trans, true,
                       batch_size);
             skip_in_trans = skip_next_in_trans;
         } else {
```

**Comment by uestccokey** [comment]
thanks, I will test tomorrow @Ttl @gcp

**Comment by l1t1** [comment]
Is  AQGO your works, that is nice.

**Comment by uestccokey** [comment]
I've tried it, but still not working. The same error..."Error in convolve3: clEnqueueNDRangeKernel: -54"

**Comment by 22nsuk** [comment]
Sorry for another question. Can you also upload the latest English version?

**Comment by uestccokey** [comment]
That is a multi-language supported version. @22nsuk .You should switch the phone's language to English.

**Comment by 22nsuk** [comment]
@uestccokey thx!

**Comment by l1t1** [comment]
expect the new version of AQ https://github.com/ymgaq/AQ/issues/103

**Comment by uestccokey** [comment]
AQGO has been updated!

1. Fix many bugs
2. Support more randomly the first x moves
3. The maximum playout limit now is 1~3200

[1.2.1.9](https://drive.google.com/open?id=1l6W52qEvj9CI_QkJ3oMZMebB5ItG-s1d)

**Comment by uestccokey** [comment]
AQGO has been updated!

1. Support Leela analysis
2. Fix many bugs

[1.2.2.1](https://drive.google.com/open?id=1S_AEIdZ7uF7s8kLNnlLsIPnHpFEbZAoW)

**Comment by uestccokey** [comment]
AQGO has been updated!

1. Leela analysis supports variation diagram
2. Leela watch can see black and white logs
3. Leela engine update to latest

[1.2.2.4](http://aqgo.ezandroid.cn/%E9%98%BFQ%E5%9B%B4%E6%A3%8B1.2.2.4-Tieba_1.apk)

**Comment by l1t1** [comment]
is the latest next  stable?

**Comment by uestccokey** [comment]
Yes.
Okhttp3 is a framework to request network. It should be the folder that SDK created by itself.

**Comment by uestccokey** [comment]
AQGO 1.2.2.7 has been updated!

1.Fix many bugs
2.Support more board and stone theme
3.Support take stone sound
4.Leela engine update to 0918

https://www.reddit.com/r/baduk/comments/9is083/aq_go_v1227_version_has_been_released_9_super/

**Comment by uestccokey** [comment]
Ah Q GO 2.0.0 has been released!

A huge update that contains tons of new features.
Strongly recommended!

http://aqgo.ezandroid.cn/AQGO_2.0.0_Github_2018-11-20.apk

**Comment by y-ich** [comment]
@uestccokey san,

When I released Go AI iOS  app recently, several people in Japan asked me about Android version.
And I told them about your app. They were glad.
Why don't you release your app on Google Play? Your app will reach more people.

And I have a question for you.
Qualcomm made snapdragon 855 public.
How many playouts per sec. do you expect for your app on this processor using 20b-224c weight(ELF)?

Thanks and cheers.

**Comment by uestccokey** [comment]
@y-ich 

Thank you for your recommendation!

Maybe next spring I will put it on Google Play. Before that I want the program is as stable and powerful as possible, and there is still a lot of work to do.

On my Samsung S9 (Qualcomm 845), use elf about 7 playouts per second.
On Qualcomm 855, I hope it can have 10 playouts per second.

**Comment by y-ich** [comment]
@uestccokey san,

I will tell people your plan.

About Qualcomm 855.
My app achieved 170 playouts per sec. on A12X Bionic.
And Qualcomm 855 should be more.
The performance of Neural Engine on A12X Bionic is 5 TOPS but the one of AI Engine on Qualcomm 855 is 7 TOPS.
I recommend you to consider TensorFlow Lite instead of OpenCL.
It will use Neural Networks API and will automatically enable The AI engine.
I guess that your app will achieve more then 200 playouts per sec.

Cheers.

**Comment by uestccokey** [comment]
@y-ich 
170 playouts! Amazing! How fast is it on other CPUs?

Thanks for your suggestion!
In fact, the current leela engine in Ah Q is a pure CPU version, without hardware acceleration. 
I also learned about TensorFlow Lite before, but I don't know how to use it in leela.

For me, maybe the speed is not the most important, because it is already difficult enough for amateur players.

**Comment by uestccokey** [comment]
@y-ich 
I just installed your app on iphone6s.
Some Chinese translations are not appropriate. I can provide some help if you need it.😆
In addition, Ah Q is also going to provide a Japanese version. Can you help me?

**Comment by y-ich** [comment]
@uestccokey san, thank you for purchasing my app!

Some user kindly provided speed information.
iPhone 5s, 1.1 N/s
iPhone 6 Plus, 1.4 N/s
iPhone X, 13-15 N/s
iPhone Xs Max, 130-160 N/s
iPad Air 2, 2.6 N/s

And I agree with you about the speed. The reason why I pursued the speed is only for ladder reading.

If you help me Chinese in my app, I will really really appreciate you.
I am using Google translation and others but mixing Go jargons leads them to strange world...^^;
My e-mail address is new.three.rs@gmail.com.
Or you can access github issues of my app if you like. https://github.com/new3Rs/a_master_of_go/issues
Please tell me any suggestions when you have time.

And of course, it is my pleasure to help Japanese for your app!
Thank you!

**Comment by uestccokey** [comment]
Ok, I have already sent you a email.😆

**Comment by uestccokey** [comment]
AhQ Go has finally been released to Google Play. 
https://play.google.com/store/apps/details?id=cn.ezandroid.aq
cheers!^^

**Comment by l1t1** [comment]
@uestccokey you may add the new trained 15b weights that won 157 into recommand weights

**Comment by uestccokey** [comment]
@l1t1 
But I don't know who trained it. I need to ask the author's permission.

**Comment by l1t1** [comment]
@evdwerf
I found the 15b weight files used in Gridmaster(http://gridmaster.tengen.nl/engines/aarch64/) are much smaller than normal quantized weights,
for example, your 157 weight is only 15M(ungzip 65,423,958 ), but the new 15b(https://github.com/gcp/leela-zero/issues/2091) is 20M(ungzip 74,532,255 ). and I opened both of them, yours data precision are only 2 digits, will it reduce the strength of the weight?

**Comment by l1t1** [comment]
@evdwerf
I downloaded 0.37 apk, after removed --cpu_only, it outputs
cl:Error clgetPlatfromIDs
Failed to provide protoceol version

**Comment by uestccokey** [comment]
@evdwerf Yes, I met the same error. No solution.

**Comment by l1t1** [comment]
other dl framework on android
https://github.com/PaddlePaddle/paddle-mobile
https://github.com/Tencent/ncnn

**Comment by evdwerf** [comment]
> @evdwerf
> I downloaded 0.37 apk, after removed --cpu_only, it outputs
> cl:Error clgetPlatfromIDs
> Failed to provide protoceol version

The latest version of GridMaster is 0.38, it's available from https://play.google.com/store/apps/details?id=nl.tengen.gridmaster. (0.37 does not have the option to completely disable timeouts, which can result in GTP not getting an answer in time on the prototcol_version command -- which IMO is a design flaw in LZ, but that's not for this thread).

I'm not sure about the "cl:Error clgetPlatfromIDs"; does your device have OpenCL support? (The engine searches for it in places like: "/system/lib/libOpenCL.so",  "/system/vendor/lib/libOpenCL.so", "/system/vendor/lib/egl/libGLES_mali.so", "/system/vendor/lib/libPVROCL.so").


> @evdwerf
> I found the 15b weight files used in Gridmaster(http://gridmaster.tengen.nl/engines/aarch64/) are much smaller than normal quantized weights,
> for example, your 157 weight is only 15M(ungzip 65,423,958 ), but the new 15b(#2091) is 20M(ungzip 74,532,255 ). and I opened both of them, yours data precision are only 2 digits, will it reduce the strength of the weight?

I used some more aggressive quantization schemes compared to the ones you sent before (not all have the same precision). I don't think there's a significant loss in strength; at least the performance in self-play is OK (I ran enough test matches).

**Comment by l1t1** [comment]
google is blocked,please attach the file  here,thanks

**Comment by evdwerf** [comment]
> google is blocked,please attach the file here,thanks

Try this: http://gridmaster.tengen.nl/temp/GridMasterFree_v0.38.apk

**Comment by l1t1** [comment]
there is a /system/vendor/lib/libOpenCL.so in my phone

**Comment by evdwerf** [comment]
Ok, that's the same as on my phone. Let's see how far you get without timeouts... Maybe you get the same error again, but it feels like we're close and perhaps some devices actually have a version of OpenCl where it does work...

**Comment by l1t1** [comment]
in 0.38, remove --cpu-only and no timeout
protocol_version 
gtp received unknown response
command:protocol_version response:unrecognizedargument:
Leela Zero 0.16  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.
failed to provide protocol version

**Comment by l1t1** [comment]
yes, I set 'debug', 'gtp i/o', and 'gtp err' in the settings, 
when I first install 0.16 engine(http://gridmaster.tengen.nl/engines/aarch64/lz-5x64q-0.16_armv8.zip.signed), it works fine.
then i remove  --cpu-only, it shows error message
 now, i add --cpu-only,but it return same error message

btw, i suggest you add a Repository for gridmaster at your github pages tp collect questions, thanks

**Comment by l1t1** [comment]
I reinstalled  0.16 engine(http://gridmaster.tengen.nl/engines/aarch64/lz-10x128q-0.16_armv8.zip.signed) , set 'debug', 'gtp i/o', and 'gtp err' in the settings, it works fine

**Comment by l1t1** [comment]
I remove  --cpu-only in 10x128 engine, it shows same error message
i add --cpu-only back  in 10x128 engine, it return same error message

**Comment by l1t1** [comment]
yes, very strange, at one time, my 0.14 engine with 20x224 also became bad(failed to provide protocol version), but it worked after many tries(switch to other engine, swtich back 0.14), <u>the 0.16 is still bad</u>
**I think I find the reason**
I placed a space before--cpu-only, after remove the space, 0.16 (5x64)also works
I placed TWO spaces after --cpu-only , after remove ONE space, 0.16 (5x64)also works
suggest new version can handle the additional spaces

**Comment by l1t1** [comment]
in 0.38, when remove --cpu-only and additional space,  set 'debug', 'gtp i/o', and 'gtp err' in the settings.  and no timeout
**the question still is**
cl:Error clgetPlatfromIDs
Failed to provide protoceol version

**Comment by evdwerf** [comment]
Sure, static linking is possible but then it only works for one device type. People that know how to cross-compile for Android could try that themselves (and please let me know if you found something that works!).

> cl:Error clgetPlatfromIDs
I saw the same error on a galaxy S9. 

> Failed to provide protocol version
This is unimportant, it is just shown because the engine crashes (from the OpenCL error) and then there is no answer to the first gtp command.

**Comment by l1t1** [comment]
what is the changelog of v0.39?

**Comment by l1t1** [comment]
I downloaded it from http://gridmaster.tengen.nl/temp/GridMasterFree_v0.38.apk , still got cl:Error clgetPlatfromIDs when remove --cpu-only

**Comment by l1t1** [comment]
some article about gpu and opencl, whether the size of array were too big for mobile gpu?
https://developer.qualcomm.com/blog/matrix-multiply-adreno-gpus-part-1-opencl-optimization
https://developer.qualcomm.com/blog/better-opencl-performance-qualcomm-adreno-gpu-memory-optimization
I found them through their chinese version
https://www.csdn.net/article/a/2016-06-09/15838600
https://www.csdn.net/article/a/2016-10-25/15841503

**Comment by l1t1** [comment]
is this useful

    
https://github.com/gcp/leela-zero/pull/2138/commits/624bd7d7dfaee5906718a06c60ac393727422fd1

**Comment by gcp** [comment]
>0.37 does not have the option to completely disable timeouts, which can result in GTP not getting an answer in time on the prototcol_version command -- which IMO is a design flaw in LZ, but that's not for this thread

Can you file an issue with some proposals?

There's no explicit point defined in the GTP spec when you should initialize (unlike UCI, which deals exactly with your problem case here). protocol_version seems obvious, but if you were intending to follow that up with name and version (very normal) that will now hang. A GUI probably also wants to lz-setoptions before the engine "hands on load".

Thinking about it and reading the spec, I think the engine has to load the network at the moment "boardsize" is sent, but that only in GTP mode. "boardsize" seems like the only comment the GUI really can't get away with sending. "clear_board" too (at least in GTP 2!), but "boardsize" makes more sense as the networks are per-size anyway.

So delaying the network load till "boardsize" when used in GTP mode might be doable.

**Comment by evdwerf** [comment]
BTW I compiled new versions for the lz-5x64 and lz9x9 packages on my site for GridMaster. They check an additional location in the search for the OpenCL libs, which might help on some 64-bit Android devices.

**Comment by l1t1** [comment]
i updated my 5*64 pkg with the new one, even if i delete   --cpu-only, it run cpu only version

**Comment by l1t1** [comment]
the screenshot is at https://userscloud.com/9sue229lm8ph

**Comment by evdwerf** [comment]
> the screenshot is at https://userscloud.com/9sue229lm8ph

You should delete the old version first (press '-' button in the settings), otherwise it might not install the new one (I didn't change the zip file name).

**Comment by l1t1** [comment]
I did as you just told, 
when i delete --cpu-only, it still run cpu-only version 
the screenshot is at https://userscloud.com/n1xxisgz79d5
https://userscloud.com/6cjufgrg1t2t

**Comment by evdwerf** [comment]
Thanks! At least it's not crashing (which it does on my phone on the first genmove, even though the OpenCL tuner phase passes just fine). I guess it simply doesn't not recognize your hardware and then falls back to cpu-only.

**Comment by l1t1** [comment]
i  wonder it show cpu only just like the windows cpu only version, see https://github.com/gcp/leela-zero/issues/2136

**Comment by l1t1** [comment]
this tool can detect opencl info
https://m.wandoujia.com/apps/com.robertwgh.opencl_z_android/download/dot?ch=detail_normal_dl

**Comment by l1t1** [comment]
when will the lz 0.17 android version engine for gridmaster release  @evdwerf

**Comment by l1t1** [comment]
https://github.com/tensorflow/tensorflow/issues/23747#issuecomment-457256006

**Comment by evdwerf** [comment]
I uploaded the new version. Default it is using --cpu-only, but if you
remove that from the arguments it will try to use openCL (which may or may
not work depending on your device's openCL implementation).

**Comment by iopq** [comment]
@evdwerf it doesn't have time to do the tuning on my phone. Fails with "failed to provide protocol version" because it times out the first time

**Comment by evdwerf** [comment]
Timeouts shouldn't be the problem here; normally that message appears
because the command is sent but not answered. I suspect it is because the
engine crashed. Look at the output from the standard error in gray.

**Comment by iopq** [comment]
In that case the tuner is failing. It does that half way through the tuning, no other error message. Probably the gpu is not powerful enough.

**Comment by evdwerf** [comment]
If you want to see some more debug information try the 5x64 downloads.


Op ma 24 jun. 2019 04:22 schreef iopq <notifications@github.com>:

**Comment by iopq** [comment]
Tuner still crashes with the 5x64 version, no other error message

**Comment by iopq** [comment]
Takes approximately 50 seconds

**Comment by evdwerf** [comment]
I'm surprised you see nothing extra with the 64x5 downloads; this suggests that the crash is different for you than what I'm used to. On my phone (an S10e) without '--cpu-only' it looks like this:

![lzOenClCrash](https://user-images.githubusercontent.com/3703860/60399457-cf644280-9b64-11e9-8f33-f89088dc9ce4.jpg)

The interesting message is the segmentation fault that occurred when it called clCreateKernel. I don't know why it happens. The moment when it happens seems random, but when the function is called often enough eventually it always happens. I'm hoping some other gpu's don't have this issue... Perhaps recent Adreno's are better? 

If you run the engine from the command line in a shell you might see a bit more (for the larger downloads, which don't have additional debug code, I can only see the segfault error if I run directly in a shell).

BTW The red line at the bottom is not interesting; it just occurs because the engine crashed without providing the protocol version.

**Comment by iopq** [comment]
Mine gets way further
![Screenshot_20190702-003331](https://user-images.githubusercontent.com/1817528/60452551-5ac2fe00-9c61-11e9-9d33-3e199fcc5212.jpg)

**Comment by evdwerf** [comment]
So it dies for some unknown reason... What type of GPU does your device have @iopq ? You might still see a bit more if you run directly in a shell, but I don't know if you have the tools in place to do that.

I would like to know what happens on devices where OpenCL is known to work with Leelaz. @Grant-Tao , @l1t1 , perhaps you could give it a try? My solution should be generic (not requiring a different binary for every GPU), but perhaps Android does not allow this (wouldn't be the first time one of google's obscure 'security' features causes problems), or it might just be problems with some specific GPU's.

**Comment by iopq** [comment]
My device is a OnePlus 3 with an Adreno 530
